name: deploy infrastructure
run-name: big-bang
on: [workflow_dispatch]
jobs:
  provision_cluster:
    runs-on: self-hosted
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Generate key"
        run: ssh-keygen -f terraform/configs/root

      - name: "Fix permissions for key"
        run: chmod 600 terraform/configs/root

      - name: "Modify cloudinit to add generate key"
        run: hash=$(cat terraform/configs/root.pub); sed -i "s|CHANGEME|${hash}|" terraform/configs/users_and_groups.cfg 

      - name: "Check if nodes are deployed"
        run: echo NODES_RUNNING=$(sudo virsh list --all | grep k8s | wc -l)>>$GITHUB_OUTPUT
        id: checker
      
      - name: "Deploy cluster"
        if: ${{ steps.checker.outputs.NODES_RUNNING == 0 }}
        run: sudo terraform -chdir=terraform init && sudo terraform -chdir=terraform plan && sudo terraform -chdir=terraform apply --auto-approve
      
      - name: "Cleanup dnsmasq"
        if: ${{ steps.checker.outputs.NODES_RUNNING != 0 }}
        run: sudo rm /var/lib/libvirt/dnsmasq/virbr0.*

      - name: "Restart machines"
        if: ${{ steps.checker.outputs.NODES_RUNNING != 0 }}
        run: or vm in $(sudo virsh list --all | grep k8s); sudo virsh reboot $vm; done
      
      - name: "Get cluster IPs"
        if: ${{ steps.health.outputs.BOOTSTRAPPED_NODES == 0 }}
        run: utils/gather_hosts.sh

      - name: "Check if cluster is configured"
        if: ${{ steps.checker.outputs.NODES_RUNNING != 0 }}
        id: health
        run: echo BOOTSTRAPPED_NODES=$(ssh -o StrictHostKeyChecking=no -i terraform/configs/root root@$(sudo virsh domifaddr k8s-master | grep -ohe "192.*" | cut -d"/" -f1) "kubectl get nodes | grep worker | wc -l")>>$GITHUB_OUTPUT
      
      - name: "Configure cluster if it's not configured"
        if: ${{ steps.health.outputs.BOOTSTRAPPED_NODES == 0 }}
        run: cd ansible; ansible-galaxy install -r roles/requirements.yml; ansible-playbook -i inventory/hosts main.yml